apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pingpong-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: daoquocquyen/pong
    newTag: 1.0.0-340c758
patches:
  - path: deployment-patch.yaml